### ISSUE TITLE
Implement the hydra_provider GRPC server 

### ISSUE THREAD

**Issue by seofernando25** [uorocketry/rgs#111]
`hydra_provider` is currently using a stub implementation for the GRPC server.

We would like to have an exposing API that allow us to:
- Check the current running configuration of `hydra_provider` (health and status)
- Change configurations (set data mode: **random,  serial port, idle**; select a desired serial port, set baud rate, etc)

And optionally a simple UI front-end for it.

It seems that a quite big refactor would have to be made for it to work as the currently `hydra_provider` architecture doesn't allow it.

**Comment by seofernando25** [comment]
Thinking about it, it would be interesting if

- `hydra_provider` without any arguments starts in an IDLE / DISCONNECTED mode
- And we could either:
  - Use the Web UI to manually change it to random/serial/idle modes and passing their proper config
  -  Use the CLI args to override the default idle mode on start-up

Thoughts?

**Comment by darrenrahnemoon** [comment]
Yeah I'm adding that. So basically the cli only takes a port for serving. Everything else is configured through the api endpoints.

**Comment by seofernando25** [comment]
Closed by #113
