### ISSUE TITLE
Purpose of client folder

### ISSUE THREAD

**Issue by SeoFernando25** [uorocketry/rgs#27]
In the root folder there is a folder called `client` with an auto generated `.svelte-kit` file.

Is there any reason for this to exist @MarwanMashaly1?
or maybe it was created by accident :thinking: 

![image](https://github.com/uorocketry/rgs/assets/26195439/6626d7ac-311f-4e7c-8430-a79d305f8b61)

**Comment by MarwanMashaly1** [comment]
yeah, I think that created by accident
