### ISSUE TITLE
Don't have RocketStatus be calculated by the client

### ISSUE THREAD

**Issue by MarwanMashaly1** [uorocketry/rgs#65]
Currently RocketStatus is being calculated client side in a component.
This is bad because if we have two or more components or even two people connected we would send repeated data.

A few possible altenatives are:
- Have it be calculated in a  [View Collection](https://pocketbase.io/docs/collections#view-collection) for RocketStatus
- Separate service for calculating those sort of metrics
- Writable that tries to calculate that using the latest data or previous data with filters (eg: sort by altitude for max altitude)

**Comment by seofernando25** [comment]
@MarwanMashaly1 after the #110 merge I removed the RocketStatus component from the ground station.

our GraphQL does provide some aggregate data to see stuff like Max ΔV, Max Altitude, etc
along with the other stuff like pressure, temp, etc

**Comment by seofernando25** [comment]
We should make another issue to recreate RocketStatus
