### ISSUE TITLE
Labjack DC Motor Driver 

### ISSUE THREAD

**Issue by NoahSprenger** [uorocketry/rgs#89]
See https://github.com/uorocketry/rocket-code-2020/blob/master/src/IO/gpio/DCMotor.cpp https://github.com/uorocketry/arduino-io-proxy/blob/master/src/dcMotorMessage.cpp

**Comment by seofernando25** [comment]
@NoahSprenger can this issue be closed as stale? Or not yet?

**Comment by NoahSprenger** [comment]
Close it as stale yeah.

**Comment by seofernando25** [comment]
Stale
